#ifndef SCANCODES_H
#define SCANCODES_H

typedef enum
{
    FF_SCANCODE_UNKNOWN = 0,
    FF_SCANCODE_A = 4,
    FF_SCANCODE_B = 5,
    FF_SCANCODE_C = 6,
    FF_SCANCODE_D = 7,
    FF_SCANCODE_E = 8,
    FF_SCANCODE_F = 9,
    FF_SCANCODE_G = 10,
    FF_SCANCODE_H = 11,
    FF_SCANCODE_I = 12,
    FF_SCANCODE_J = 13,
    FF_SCANCODE_K = 14,
    FF_SCANCODE_L = 15,
    FF_SCANCODE_M = 16,
    FF_SCANCODE_N = 17,
    FF_SCANCODE_O = 18,
    FF_SCANCODE_P = 19,
    FF_SCANCODE_Q = 20,
    FF_SCANCODE_R = 21,
    FF_SCANCODE_S = 22,
    FF_SCANCODE_T = 23,
    FF_SCANCODE_U = 24,
    FF_SCANCODE_V = 25,
    FF_SCANCODE_W = 26,
    FF_SCANCODE_X = 27,
    FF_SCANCODE_Y = 28,
    FF_SCANCODE_Z = 29,

    FF_SCANCODE_1 = 30,
    FF_SCANCODE_2 = 31,
    FF_SCANCODE_3 = 32,
    FF_SCANCODE_4 = 33,
    FF_SCANCODE_5 = 34,
    FF_SCANCODE_6 = 35,
    FF_SCANCODE_7 = 36,
    FF_SCANCODE_8 = 37,
    FF_SCANCODE_9 = 38,
    FF_SCANCODE_0 = 39,

    FF_SCANCODE_RETURN = 40,
    FF_SCANCODE_ESCAPE = 41,
    FF_SCANCODE_BACKSPACE = 42,
    FF_SCANCODE_TAB = 43,
    FF_SCANCODE_SPACE = 44,

    FF_SCANCODE_MINUS = 45,
    FF_SCANCODE_EQUALS = 46,
    FF_SCANCODE_LEFTBRACKET = 47,
    FF_SCANCODE_RIGHTBRACKET = 48,
    FF_SCANCODE_BACKSLASH = 49,
    FF_SCANCODE_NONUSHASH = 50,
    FF_SCANCODE_SEMICOLON = 51,
    FF_SCANCODE_APOSTROPHE = 52,
    FF_SCANCODE_GRAVE = 53,
    FF_SCANCODE_COMMA = 54,
    FF_SCANCODE_PERIOD = 55,
    FF_SCANCODE_SLASH = 56,

    FF_SCANCODE_CAPSLOCK = 57,

    FF_SCANCODE_F1 = 58,
    FF_SCANCODE_F2 = 59,
    FF_SCANCODE_F3 = 60,
    FF_SCANCODE_F4 = 61,
    FF_SCANCODE_F5 = 62,
    FF_SCANCODE_F6 = 63,
    FF_SCANCODE_F7 = 64,
    FF_SCANCODE_F8 = 65,
    FF_SCANCODE_F9 = 66,
    FF_SCANCODE_F10 = 67,
    FF_SCANCODE_F11 = 68,
    FF_SCANCODE_F12 = 69,

    FF_SCANCODE_PRINTSCREEN = 70,
    FF_SCANCODE_SCROLLLOCK = 71,
    FF_SCANCODE_PAUSE = 72,
    FF_SCANCODE_INSERT = 73,
    FF_SCANCODE_HOME = 74,
    FF_SCANCODE_PAGEUP = 75,
    FF_SCANCODE_DELETE = 76,
    FF_SCANCODE_END = 77,
    FF_SCANCODE_PAGEDOWN = 78,
    FF_SCANCODE_RIGHT = 79,
    FF_SCANCODE_LEFT = 80,
    FF_SCANCODE_DOWN = 81,
    FF_SCANCODE_UP = 82,

    FF_SCANCODE_NUMLOCKCLEAR = 83,
    FF_SCANCODE_KP_DIVIDE = 84,
    FF_SCANCODE_KP_MULTIPLY = 85,
    FF_SCANCODE_KP_MINUS = 86,
    FF_SCANCODE_KP_PLUS = 87,
    FF_SCANCODE_KP_ENTER = 88,
    FF_SCANCODE_KP_1 = 89,
    FF_SCANCODE_KP_2 = 90,
    FF_SCANCODE_KP_3 = 91,
    FF_SCANCODE_KP_4 = 92,
    FF_SCANCODE_KP_5 = 93,
    FF_SCANCODE_KP_6 = 94,
    FF_SCANCODE_KP_7 = 95,
    FF_SCANCODE_KP_8 = 96,
    FF_SCANCODE_KP_9 = 97,
    FF_SCANCODE_KP_0 = 98,
    FF_SCANCODE_KP_PERIOD = 99,

    FF_SCANCODE_NONUSBACKSLASH = 100,
    FF_SCANCODE_APPLICATION = 101,
    FF_SCANCODE_POWER = 102,
    FF_SCANCODE_KP_EQUALS = 103,
    FF_SCANCODE_F13 = 104,
    FF_SCANCODE_F14 = 105,
    FF_SCANCODE_F15 = 106,
    FF_SCANCODE_F16 = 107,
    FF_SCANCODE_F17 = 108,
    FF_SCANCODE_F18 = 109,
    FF_SCANCODE_F19 = 110,
    FF_SCANCODE_F20 = 111,
    FF_SCANCODE_F21 = 112,
    FF_SCANCODE_F22 = 113,
    FF_SCANCODE_F23 = 114,
    FF_SCANCODE_F24 = 115,
    FF_SCANCODE_EXECUTE = 116,
    FF_SCANCODE_HELP = 117,
    FF_SCANCODE_MENU = 118,
    FF_SCANCODE_SELECT = 119,
    FF_SCANCODE_STOP = 120,
    FF_SCANCODE_AGAIN = 121,   /**< redo */
    FF_SCANCODE_UNDO = 122,
    FF_SCANCODE_CUT = 123,
    FF_SCANCODE_COPY = 124,
    FF_SCANCODE_PASTE = 125,
    FF_SCANCODE_FIND = 126,
    FF_SCANCODE_MUTE = 127,
    FF_SCANCODE_VOLUMEUP = 128,
    FF_SCANCODE_VOLUMEDOWN = 129,

    FF_SCANCODE_KP_COMMA = 133,
    FF_SCANCODE_KP_EQUALSAS400 = 134,

    FF_SCANCODE_INTERNATIONAL1 = 135,
    FF_SCANCODE_INTERNATIONAL2 = 136,
    FF_SCANCODE_INTERNATIONAL3 = 137,
    FF_SCANCODE_INTERNATIONAL4 = 138,
    FF_SCANCODE_INTERNATIONAL5 = 139,
    FF_SCANCODE_INTERNATIONAL6 = 140,
    FF_SCANCODE_INTERNATIONAL7 = 141,
    FF_SCANCODE_INTERNATIONAL8 = 142,
    FF_SCANCODE_INTERNATIONAL9 = 143,
    FF_SCANCODE_LANG1 = 144,
    FF_SCANCODE_LANG2 = 145,
    FF_SCANCODE_LANG3 = 146,
    FF_SCANCODE_LANG4 = 147,
    FF_SCANCODE_LANG5 = 148,
    FF_SCANCODE_LANG6 = 149, /**< reserved */
    FF_SCANCODE_LANG7 = 150, /**< reserved */
    FF_SCANCODE_LANG8 = 151, /**< reserved */
    FF_SCANCODE_LANG9 = 152, /**< reserved */

    FF_SCANCODE_ALTERASE = 153, /**< Erase-Eaze */
    FF_SCANCODE_SYSREQ = 154,
    FF_SCANCODE_CANCEL = 155,
    FF_SCANCODE_CLEAR = 156,
    FF_SCANCODE_PRIOR = 157,
    FF_SCANCODE_RETURN2 = 158,
    FF_SCANCODE_SEPARATOR = 159,
    FF_SCANCODE_OUT = 160,
    FF_SCANCODE_OPER = 161,
    FF_SCANCODE_CLEARAGAIN = 162,
    FF_SCANCODE_CRSEL = 163,
    FF_SCANCODE_EXSEL = 164,

    FF_SCANCODE_KP_00 = 176,
    FF_SCANCODE_KP_000 = 177,
    FF_SCANCODE_THOUSANDSSEPARATOR = 178,
    FF_SCANCODE_DECIMALSEPARATOR = 179,
    FF_SCANCODE_CURRENCYUNIT = 180,
    FF_SCANCODE_CURRENCYSUBUNIT = 181,
    FF_SCANCODE_KP_LEFTPAREN = 182,
    FF_SCANCODE_KP_RIGHTPAREN = 183,
    FF_SCANCODE_KP_LEFTBRACE = 184,
    FF_SCANCODE_KP_RIGHTBRACE = 185,
    FF_SCANCODE_KP_TAB = 186,
    FF_SCANCODE_KP_BACKSPACE = 187,
    FF_SCANCODE_KP_A = 188,
    FF_SCANCODE_KP_B = 189,
    FF_SCANCODE_KP_C = 190,
    FF_SCANCODE_KP_D = 191,
    FF_SCANCODE_KP_E = 192,
    FF_SCANCODE_KP_F = 193,
    FF_SCANCODE_KP_XOR = 194,
    FF_SCANCODE_KP_POWER = 195,
    FF_SCANCODE_KP_PERCENT = 196,
    FF_SCANCODE_KP_LESS = 197,
    FF_SCANCODE_KP_GREATER = 198,
    FF_SCANCODE_KP_AMPERSAND = 199,
    FF_SCANCODE_KP_DBLAMPERSAND = 200,
    FF_SCANCODE_KP_VERTICALBAR = 201,
    FF_SCANCODE_KP_DBLVERTICALBAR = 202,
    FF_SCANCODE_KP_COLON = 203,
    FF_SCANCODE_KP_HASH = 204,
    FF_SCANCODE_KP_SPACE = 205,
    FF_SCANCODE_KP_AT = 206,
    FF_SCANCODE_KP_EXCLAM = 207,
    FF_SCANCODE_KP_MEMSTORE = 208,
    FF_SCANCODE_KP_MEMRECALL = 209,
    FF_SCANCODE_KP_MEMCLEAR = 210,
    FF_SCANCODE_KP_MEMADD = 211,
    FF_SCANCODE_KP_MEMSUBTRACT = 212,
    FF_SCANCODE_KP_MEMMULTIPLY = 213,
    FF_SCANCODE_KP_MEMDIVIDE = 214,
    FF_SCANCODE_KP_PLUSMINUS = 215,
    FF_SCANCODE_KP_CLEAR = 216,
    FF_SCANCODE_KP_CLEARENTRY = 217,
    FF_SCANCODE_KP_BINARY = 218,
    FF_SCANCODE_KP_OCTAL = 219,
    FF_SCANCODE_KP_DECIMAL = 220,
    FF_SCANCODE_KP_HEXADECIMAL = 221,

    FF_SCANCODE_LCTRL = 224,
    FF_SCANCODE_LSHIFT = 225,
    FF_SCANCODE_LALT = 226, /**< alt, option */
    FF_SCANCODE_LGUI = 227, /**< windows, command (apple), meta */
    FF_SCANCODE_RCTRL = 228,
    FF_SCANCODE_RSHIFT = 229,
    FF_SCANCODE_RALT = 230, /**< alt gr, option */
    FF_SCANCODE_RGUI = 231, /**< windows, command (apple), meta */

    FF_SCANCODE_MODE = 257,    /**< I'm not sure if this is really not covered
                                 *   by any of the above, but since there's a
                                 *   special KMOD_MODE for it I'm adding it here
                                 */

    /* @} *//* Usage page 0x07 */

    /**
     *  \name Usage page 0x0C
     *
     *  These values are mapped from usage page 0x0C (USB consumer page).
     */
    /* @{ */

    FF_SCANCODE_AUDIONEXT = 258,
    FF_SCANCODE_AUDIOPREV = 259,
    FF_SCANCODE_AUDIOSTOP = 260,
    FF_SCANCODE_AUDIOPLAY = 261,
    FF_SCANCODE_AUDIOMUTE = 262,
    FF_SCANCODE_MEDIASELECT = 263,
    FF_SCANCODE_WWW = 264,
    FF_SCANCODE_MAIL = 265,
    FF_SCANCODE_CALCULATOR = 266,
    FF_SCANCODE_COMPUTER = 267,
    FF_SCANCODE_AC_SEARCH = 268,
    FF_SCANCODE_AC_HOME = 269,
    FF_SCANCODE_AC_BACK = 270,
    FF_SCANCODE_AC_FORWARD = 271,
    FF_SCANCODE_AC_STOP = 272,
    FF_SCANCODE_AC_REFRESH = 273,
    FF_SCANCODE_AC_BOOKMARKS = 274,



    FF_SCANCODE_BRIGHTNESSDOWN = 275,
    FF_SCANCODE_BRIGHTNESSUP = 276,
    FF_SCANCODE_DISPLAYSWITCH = 277, /**< display mirroring/dual display
                                           switch, video mode switch */
    FF_SCANCODE_KBDILLUMTOGGLE = 278,
    FF_SCANCODE_KBDILLUMDOWN = 279,
    FF_SCANCODE_KBDILLUMUP = 280,
    FF_SCANCODE_EJECT = 281,
    FF_SCANCODE_SLEEP = 282,

    FF_SCANCODE_APP1 = 283,
    FF_SCANCODE_APP2 = 284,



    FF_NUM_SCANCODES = 512 /**< not a key, just marks the number of scancodes
                                 for array bounds */
} FF_Scancode;

#endif /* _SCANCODES */
